version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Asia/Chongqing
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: history
    versions:
    - "> 4.10.1"
